### ISSUE TITLE
2.1.0 potentially breaking change

### ISSUE THREAD

**Issue by makepanic** [salsify/ember-debug-logger#19]
Hi,
thanks for maintaining this addon. 

It looks like 2.1.0 moved to ember-auto-import.
This uses debug directly from npm.

Sadly ember-auto-import isn't [transpiling packages](https://github.com/ef4/ember-auto-import/issues/41). This means because debug uses ES6 it will break in older browser which were previously supported, e.g. IE11.

**Comment by dfreeman** [comment]
Thanks reporting this @makepanic! I totally missed that debug was using ES6 features in the published package. We should probably go back to using `debug-dist`, in that case.

**Comment by dfreeman** [comment]
Alternatively, we could drop back to `debug@^3` — the breaking syntax was added in v4 of the library.

**Comment by makepanic** [comment]
I think going to `debug@^3` would be a good solution. 

`debug-dist` looks pretty outdated compared to the [last `debug@^3` release](https://github.com/visionmedia/debug/tree/3.2.6).

I can open a PR for it, if you want.

**Comment by dfreeman** [comment]
I just opened a PR before I came back and saw your comment—thanks for the offer, though! I'll cut a bugfix release as soon as everything is green there.

**Comment by dfreeman** [comment]
Should be all set in `ember-debug-logger@2.1.1` — thanks again for reporting this!
