### ISSUE TITLE
Ember 2.x support

### ISSUE THREAD

**Issue by dfreeman** [salsify/ember-debug-logger#2]
Ideally this project should support both the 1.13.x and 2.x versions of Ember. This should be doable as long as we're careful about the initializer signature, it's just a matter of someone finding the time to do it (likely updating the `ember-try` configuration to keep us honest).

See also #1 (/cc @albertovasquez)

**Comment by Ramblurr** [comment]
So debug-logger doesn't currently support 2.x? I was just about to check it out in my 2.x project.

**Comment by albertovasquez** [comment]
Yes it will work @Ramblurr just has some deprecation errors is all.  I'm sure it will be taken care of by the time the functionality is removed from ember.

**Comment by dfreeman** [comment]
Published as `0.2.0`
