### ISSUE TITLE
Using in an addon

### ISSUE THREAD

**Issue by erichonkanen** [salsify/ember-debug-logger#9]
hey I tried installing this in an addon but it seems like the underlying debug library isn't available on window.debug..

anything I might be missing?

ps it looks like the `debug-dist` lib is ~80 commits behind the main library...

**Comment by dfreeman** [comment]
>  it seems like the underlying debug library isn't available on window.debug..

We're using this in several internal addons and haven't ever run into any issues with it just working out of the box, as far as I know. Just to confirm, you've got it in your addon's `dependencies`, not `devDependencies`?

> it looks like the debug-dist lib is ~80 commits behind the main library

Yep, I should probably cut a new release of that...

**Comment by erichonkanen** [comment]
hey, yes I've tried both as dependency and dev dependency.. in each case if I'm e.g. debugger inside a route in my app, `window.debug == ƒ debug(function) { [Command Line API] } (chrome debug)`

I have this working already inside our app just fine but we want to move it into our internal addon... not sure why it's not attaching to window! any ideas?

**Comment by erichonkanen** [comment]
here is screenshot of my console after reinstalling using `yarn add ember-debug-logger` inside my addon:
![image](https://user-images.githubusercontent.com/230757/34811870-ef8ac2cc-f657-11e7-9fb9-505c6ed94a2c.png)

**Comment by dfreeman** [comment]
Super weird! Can you confirm whether `debug-dist` is making it into your `vendor.js` at all?

**Comment by erichonkanen** [comment]
how would I know? I just did `ls /vendor` from my addon root and it's empty...

**Comment by dfreeman** [comment]
The easiest way is probably to run `ember build` and then check `dist/assets/vendor.js` for some likely-unique snippet of text from `debug-dist`, e.g. the string `lightseagreen` shows up as one of the colors it cycles through for the log tags.

![image](https://user-images.githubusercontent.com/108688/34883688-52cdac92-f788-11e7-99a7-842361447073.png)

**Comment by erichonkanen** [comment]
![image](https://user-images.githubusercontent.com/230757/34885495-058a2b1c-f775-11e7-88ba-2fb4f73127b2.png)
looks like it's there! could the version of ember in the app or our addon have anything to do with it? not sure how debug is set onto window.debug but something is off :/ (`2.16.x`)

**Comment by dfreeman** [comment]
```sh
ember addon test-addon --skip-npm
cd test-addon
yarn add ember-debug-logger

cd ..

ember new test-app --skip-npm
cd test-app
yarn add link:../test-addon
ember serve
```

![image](https://user-images.githubusercontent.com/108688/34889455-07f6a14c-f79c-11e7-823d-b49d33c17b00.png)

**Comment by erichonkanen** [comment]
@dfreeman where do I check for `module` and `define.amd`? I put a debugger inside the addon/initializers/logger.js file and get: `module is not defined`
![image](https://user-images.githubusercontent.com/230757/34922256-54de6312-f942-11e7-957b-4bef43691344.png)

**Comment by erichonkanen** [comment]
not sure if related? https://github.com/ember-cli/ember-cli/pull/5976

**Comment by erichonkanen** [comment]
https://gist.github.com/foxnewsnetwork/276eca2274a328b085ee54926e609cdb

**Comment by dfreeman** [comment]
Not having `module` and `define.amd` is a good thing for our purposes here—it means `window.debug` _should_ be getting assigned (though I'm increasingly baffled as to why it's not).

If you're able to provide a reproduction of your issue, I'd be happy to dig in and try to understand what's happening, but at this point I'm out of ideas for what could be going wrong and I haven't been able to reproduce it myself in a fresh addon.

**Comment by erichonkanen** [comment]
decided against using it in the addon since we couldnt get it working.. maybe adding to an existing addon is different from a brand new addon idk
